### ISSUE TITLE
Attachments are not included in report when using NUnit

### ISSUE THREAD

**Issue by cdapprich-bt** [maxbahr/specflow-trx-to-html-action#22]
The screenshots and description on Marketplace seem to indicate that any images/attachments added using the output helper will be directly included/embedded within the test results. However, this isn't the case when using the NUnit framework instead of XUnit. I don't have an example project to reproduce the issue, but I could create one if necessary. 

Is this action intended to support NUnit? If so, I'd very much like this to be fixed. Thank you in advance!

**Comment by maxbahr** [comment]
Hi 
thanks for checking the plugin. 
It might happen that NUnit is not fully supported. I tested it on XUnit. 
I will try to check this and fix shortly.

**Comment by cdapprich-bt** [comment]
This worked for me, thanks much!
